### ISSUE TITLE
Executable/Version Support

### ISSUE THREAD

**Issue by DanzaG** [Tonyx97/Tomb-Raider-II-Multiplayer-Mod#11]
I notice currently this only supports Multi-Patch (a.k.a. clean Steam/GOG version).

Quite a lot (particularly in TombRunner community) use different exes. These are Eidos Premier Collection and UK Box.

UK Box executable is the most popular. Enabling support for the 3 common versions - EPC, UK Box and Multi-Patch would be great.

UK Box has more "PS1-like mechanics" - this is arguably the most "original" version of the game, at least when compared to its PS1 counterpart.

EPC has a different momentum mechanism when stumbling by jumping into a wall for example. If you jump into something, a lot of the time you will stumble forwards and not backwards.

MultiPatch is very similar to the above, just that jumping in low spaces is broken.

**Comment by Tonyx97** [comment]
If you can send me the executables of all the versions would be great, for the TR III as well if you have them so I can support them at the beginning of the release of TR III Multiplayer mod I've been planning to do.

**Comment by DanzaG** [comment]
I will collect them up and send them.
