### ISSUE TITLE
Multiplayer Mode Suggestion - Fire/Infection/Virus

### ISSUE THREAD

**Issue by DanzaG** [Tonyx97/Tomb-Raider-II-Multiplayer-Mod#12]
Single player beings infected with no weapons, but is set on fire.

This player must set all the other players on fire.

Last lara standing wins.

**Comment by Tonyx97** [comment]
Do you mean a gamemode where players are on fire and the last one standing wins? If so, how would this work exactly? How do players set other players on fire?

**Comment by DanzaG** [comment]
@Tonyx97 proximity, the only problem is the damage the fire does. Maybe we can restrict that/reduce it to 0?

**Comment by Tonyx97** [comment]
Well the point of fire is killing the players but yes, there is a way to reduce the damage of the fire so it's not that aggressive. I don't have any plans on specific gamemodes but I can take a look tomorrow about the fire damage and update the source with some fire utils functions.

**Comment by DanzaG** [comment]
Thats awesome yeah, im happy to implement the specific gamemode logic.
